spring:
  application:
    name: heifer-common-apisix-example
  jackson:
    default-property-inclusion: non_null
    generator:
      WRITE_BIGDECIMAL_AS_PLAIN: true
    serialization:
      INDENT_OUTPUT: false
    deserialization:
      READ_ENUMS_USING_TO_STRING: true
  cloud:
    nacos:
      server-addr: nuc8i7.wcj.plus:8848
  zipkin:
    base-url: http://nuc8i7.wcj.plus:9411/
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 0

heifer:
  apisix:
    server-addr: http://nuc8i7.wcj.plus:9080
    server-path: apisix/admin/
    token: edd1c9f034335f136f87ad84b625c8f1
