spring:
  application:
    name: heifer-plugin-aliyun-oss-example
heifer:
  aliyun:
    access-id: xxx
    access-key: xxx
    oss:
      beautiful-senior:
        access-id: ${heifer.aliyun.access-id}
        access-key: ${heifer.aliyun.access-key}
        bucket: beautiful-senior    # 这个便宜呀,用这个
        #      bucket: beautiful-senior   # 这个贵呀,不要用这个
        endpoint: oss-cn-hangzhou.aliyuncs.com
        host: https://${heifer.aliyun.oss.bucket}.${heifer.aliyun.oss.endpoint}
        expire: 600000
      heifer-oss-private1:
        access-id: ${heifer.aliyun.access-id}
        access-key: ${heifer.aliyun.access-key}
        bucket: heifer-oss-private1    # 这个便宜呀,用这个
        #      bucket: beautiful-senior   # 这个贵呀,不要用这个
        endpoint: oss-cn-hangzhou.aliyuncs.com
        host: https://${heifer.aliyun.oss.bucket}.${heifer.aliyun.oss.endpoint}
        expire: 600000