heifer:
  jasypt:
    encryptor:
      password: xxxxxxxx
  jwt:
    key: ENC(6LnQKQpmSOTHAZHHq6sRC5PDEVYxrJooiTe/tJNT/cEddTj9P8gvMiiw/iCJ+FlL)
    ttl: 6000000000
    remember: 604800000
  security:
    ignoring:
      get:
      post:
        - "/api/auth/login"
        - "/api/auth/logout"
      delete:
      put:
      head:
      patch:
      options:
      trace:
      pattern:
        - "/api/auth/*"
        - "/api/auth/**"
        - "/test/*"
        - "/doc"
        - "/swagger-resources/**"
        - "/swagger-ui/**"
        - "/swagger-ui/*"
        - "/v3/api-docs/**"


jasypt:
  encryptor:
    password: xxxxxxxx
server:
  port: 9090
  servlet:
    session:
      # 关闭session持久化
      persistent: false
      # session会话保持时间
      timeout: 1
      cookie:
        # cookie最大数
        max-age: 0
      tracking-modes:
spring:
  application:
    name: heifer-boot
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(WALyQUsObPa17M8MI3PbKjty4Wp+u7eMZHbstE6dP6d5hLBdgK9KiDrRMk/f5ceLvEed3HW0oO2HEROHiP16NzcKY2H9gJK9BDevM2aRpdBemUrnC35WSxf1FoW9BSwW)
    username: ENC(vLxFiSnkM5sVkZr5O+lE+KakAkXdb5KesPFTfRWHm061AFONSp5Teb7OrDQ/nIhy)
    password: ENC(tbbsGbnVkScc4qhEIyupNruL0OMj1aezdQQ8yovV6si8jcawh9NxmXY/tbQI18ek)
  redis:
    host: ENC(GQUVUG7oJgQuAx+ZgW8IY7jaDAr0lUjA4U/OUPNaHYzBUWSlpn5xG6xHtFWTlCMK)
    password: ENC(3O0bUjnbXwrA3PSf1CdkDoPFyi4PRsFKzjR24931rb8lTjVpmGyjy329uw1s7p+X)
    port: 6379
    # 连接超时时间（记得添加单位，Duration）
    timeout: 10000ms
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    # database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss
      time: yyyy-MM-dd HH:mm:ss
  webflux:
    format:
      date: yyyy-MM-dd HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss
      time: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null
    generator:
      WRITE_NUMBERS_AS_STRINGS: true
      WRITE_BIGDECIMAL_AS_PLAIN: true
  gson:
    date-format: yyyy-MM-dd HH:mm:ss
  session:
    # session 类型，
    store-type: none
    # session会话保持时间
    timeout: 0
custom:
  config:
    ignores:
      # 需要过滤的 post 请求
      post:
        - "/api/auth/login"
        - "/api/auth/logout"
      # 需要过滤的请求，不限方法
      pattern:
        - "/api/auth/*"
        - "/api/auth/**"
        - "/test/*"
        - "/doc"
        - "/swagger-resources/**"
        - "/swagger-ui/**"
        - "/swagger-ui/*"
        - "/v3/api-docs/**"
#logging:
#  level:
#    plus.wcj.heifer.boot.common.security: debug
#    org.springframework.security: debug

