heifer:
  client:
    id: 1
    name: 小魏的管理端
  jwt:
    # 至少需要32个字符哦
    key: ENC(cq4oLNrwaJ07l9fK8d9Ms9m1h2jaJ3VHLKGes8CU3NwuRQNEqkzaJd6TGs5vcgvAIacFdGtJsGPxFq9jcBh471T964aT9I/2KrvKZhiDzQ4=)
    # 10分钟 毫秒（millisecond）
    ttl: 6000000000
    # 7天 毫秒（millisecond）
    remember: 604800000
  aliyun:
    access-id: ENC(8VepeRaPD2ZwpYvIaJidQ3IDLVPb6niDIkuHcsmzgi6IJXWU8a4gjTUi50gi28XpWmZ0Tm8mrgR10BniiqOZgg==)
    access-key: ENC(PAv8lWyP2dzZQDhrN/RGAFhOP0dILshK9DTdhIRoyNk4jh37pYEEQ+WCMpiQ3ITP7noI2EO+p2TgxUmrofaeNA==)
    oss:
      access-id: ${heifer.aliyun.access-id}
      access-key: ${heifer.aliyun.access-key}
      bucket: heifer    # 这个便宜呀,用这个
      #      bucket: beautiful-senior   # 这个贵呀,不要用这个
      endpoint: oss-cn-hangzhou.aliyuncs.com
      host: https://${heifer.aliyun.oss.bucket}.${heifer.aliyun.oss.endpoint}
      expire: 600000
    sms:
      access-id: ENC(6Aw37mPcUYV3kRC0m/co12SP506ng/QvpDCur4sYJFUK09GLxNs52zCNICjw3M2jTaAq8CAt2gbKp9+nbDVLiA==)
      access-key: ENC(HeHGeO5dD0VRZbmKSqVUVKATaB7m9e0Q1OGXPHRoS5QGrAY3uBp8LNv1mgu08y+JWXS+Y6V9Gqo3uW8rjgsufA==)
      sign-name: 简氏科技
  security:
    ignoring:
      get:
      post:
      delete:
      put:
      head:
      patch:
      options:
      trace:
      pattern:
  cache:
    redis:
      time-offset-to-live: 1h
jasypt:
  encryptor:
    password: xxxxxxxxx
server:
  port: 9090
  servlet:
    session:
      # 关闭session持久化
      persistent: false
      # session会话保持时间
      timeout: 0
      cookie:
        # cookie最大数
        max-age: 0
      tracking-modes:
#  tomcat: 需要后期调优
spring:
  application:
    name: heifer-boot
  profiles:
    active: @spring.profiles.active@
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(WALyQUsObPa17M8MI3PbKjty4Wp+u7eMZHbstE6dP6d5hLBdgK9KiDrRMk/f5ceLvEed3HW0oO2HEROHiP16NzcKY2H9gJK9BDevM2aRpdBemUrnC35WSxf1FoW9BSwW)
    username: ENC(vLxFiSnkM5sVkZr5O+lE+KakAkXdb5KesPFTfRWHm061AFONSp5Teb7OrDQ/nIhy)
    password: ENC(tbbsGbnVkScc4qhEIyupNruL0OMj1aezdQQ8yovV6si8jcawh9NxmXY/tbQI18ek)
  redis:
    host: ENC(GQUVUG7oJgQuAx+ZgW8IY7jaDAr0lUjA4U/OUPNaHYzBUWSlpn5xG6xHtFWTlCMK)
    password: ENC(3O0bUjnbXwrA3PSf1CdkDoPFyi4PRsFKzjR24931rb8lTjVpmGyjy329uw1s7p+X)
    port: 6379
    # 连接超时时间（记得添加单位，Duration）
    timeout: 10000ms
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
  data:
    mongodb:
      host: ENC(ROwRdy9aQJocAtpf3YxfttoXm4/ScpnToJN0EN2aGU2/v4KsqbZd8GuDxPTGu1Av)
      port: 27017
      username: ENC(t/UD+GZh+a7Ta8fPAwe6+GR3aUPgA4fBk5k/AIFWMiBTESZysnK4gkdAe2FSKwNS)
      password: ENC(7i2Yc1/ewoTKmauyaLtooXzrOz4mSzyaDtuakmMxlZBxfdSPJsA0vEYO8KudMfHb)
      database: ENC(WsNUKnnlO68E2qsfzfq+xOeW7R714+n7t0l2AtAQsxTISkHG9ndMTFWkXQBmnEvN)
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss
      time: yyyy-MM-dd HH:mm:ss
    throw-exception-if-no-handler-found: true
  webflux:
    format:
      date: yyyy-MM-dd HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss
      time: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null
    generator:
      WRITE_NUMBERS_AS_STRINGS: true
      WRITE_BIGDECIMAL_AS_PLAIN: true
    serialization:
      INDENT_OUTPUT: false
  gson:
    date-format: yyyy-MM-dd HH:mm:ss
  session:
    # session 类型，
    store-type: none
    # session会话保持时间
    timeout: 0
#  sql:
#    init:
#      schema-locations: classpath*:/sql/heifer_boot_schema.sql
#      data-locations: classpath*:/sql/heifer_boot_data.sql
#      mode: never
  cache:
    redis:
      cache-null-values: true
      time-to-live: 1h
      time-offset-to-live: 1h
  main:
    allow-bean-definition-overriding: false
  messages:
    basename: i18n/messages
  web:
    resources:
      add-mappings: false
mybatis-plus:
  # 检查配置文件
  check-config-location: true
  # xml影射路径
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
    # 关闭一级缓存
    local-cache-scope: statement
    # 关闭二级缓存
    cache-enabled: false
    # 枚举类型处理方式
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
    # MyBatis 自动映射时未知列或未知属性处理策略
    auto-mapping-unknown-column-behavior: failing
  global-config:
    db-config:
      # id生成类型
      id-type: assign_id
      # 表名是否使用驼峰转下划线命名,只对表名生效
      table-underline: false