heifer:
  jwt:
    # 至少需要32个字符哦
    key: ENC(cq4oLNrwaJ07l9fK8d9Ms9m1h2jaJ3VHLKGes8CU3NwuRQNEqkzaJd6TGs5vcgvAIacFdGtJsGPxFq9jcBh471T964aT9I/2KrvKZhiDzQ4=)
    # 10分钟 毫秒（millisecond）
    ttl: 6000000000
    # 7天 毫秒（millisecond）
    remember: 604800000
  aliyun:
    access-id: ENC(8VepeRaPD2ZwpYvIaJidQ3IDLVPb6niDIkuHcsmzgi6IJXWU8a4gjTUi50gi28XpWmZ0Tm8mrgR10BniiqOZgg==)
    access-key: ENC(PAv8lWyP2dzZQDhrN/RGAFhOP0dILshK9DTdhIRoyNk4jh37pYEEQ+WCMpiQ3ITP7noI2EO+p2TgxUmrofaeNA==)
    oss:
      access-id: ${heifer.aliyun.access-id}
      access-key: ${heifer.aliyun.access-key}
      bucket: heifer    # 这个便宜呀,用这个
      endpoint: oss-cn-hangzhou.aliyuncs.com
      host: https://${heifer.aliyun.oss.bucket}.${heifer.aliyun.oss.endpoint}
      expire: 600000
    sms:
      access-id: ENC(6Aw37mPcUYV3kRC0m/co12SP506ng/QvpDCur4sYJFUK09GLxNs52zCNICjw3M2jTaAq8CAt2gbKp9+nbDVLiA==)
      access-key: ENC(HeHGeO5dD0VRZbmKSqVUVKATaB7m9e0Q1OGXPHRoS5QGrAY3uBp8LNv1mgu08y+JWXS+Y6V9Gqo3uW8rjgsufA==)
      sign-name: 简氏科技
  security:
    ignoring:
      get:
        # oss 授权测试
        - "/oss/policy"
        - "/favicon.ico"
        - "/auth/info"
      post:
        - "/auth/login"
        - "/auth/logout"
        - "/auth/sign-on"
      delete:
      put:
      head:
      patch:
      options:
      trace:
      pattern:
        # swagger
        - "/api/auth/*"
        - "/api/auth/**"
        - "/test/*"
        - "/doc"
        - "/swagger-resources/**"
        - "/swagger-ui/**"
        - "/swagger-ui/*"
        - "/v3/api-docs/**"
        - "/v2/api-docs"
        # 静态文件
        - "/oss/**"
jasypt:
  encryptor:
    password: xxxxxxxxx
server:
  port: 9090
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(WALyQUsObPa17M8MI3PbKjty4Wp+u7eMZHbstE6dP6d5hLBdgK9KiDrRMk/f5ceLvEed3HW0oO2HEROHiP16NzcKY2H9gJK9BDevM2aRpdBemUrnC35WSxf1FoW9BSwW)
    username: ENC(vLxFiSnkM5sVkZr5O+lE+KakAkXdb5KesPFTfRWHm061AFONSp5Teb7OrDQ/nIhy)
    password: ENC(tbbsGbnVkScc4qhEIyupNruL0OMj1aezdQQ8yovV6si8jcawh9NxmXY/tbQI18ek)
  redis:
    host: ENC(GQUVUG7oJgQuAx+ZgW8IY7jaDAr0lUjA4U/OUPNaHYzBUWSlpn5xG6xHtFWTlCMK)
    password: ENC(3O0bUjnbXwrA3PSf1CdkDoPFyi4PRsFKzjR24931rb8lTjVpmGyjy329uw1s7p+X)
    port: 6379
    # 连接超时时间（记得添加单位，Duration）
    timeout: 10000ms
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 0
  data:
    mongodb:
      host: ENC(ROwRdy9aQJocAtpf3YxfttoXm4/ScpnToJN0EN2aGU2/v4KsqbZd8GuDxPTGu1Av)
      port: 27017
      username: ENC(t/UD+GZh+a7Ta8fPAwe6+GR3aUPgA4fBk5k/AIFWMiBTESZysnK4gkdAe2FSKwNS)
      password: ENC(7i2Yc1/ewoTKmauyaLtooXzrOz4mSzyaDtuakmMxlZBxfdSPJsA0vEYO8KudMfHb)
      database: ENC(WsNUKnnlO68E2qsfzfq+xOeW7R714+n7t0l2AtAQsxTISkHG9ndMTFWkXQBmnEvN)