server:
  port: 9090
spring:
  application:
    name: heifer-boot
  datasource:
    name: defaultDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/heifer_boot?serverTimezone=UTC
    password: root
    username: root
custom:
  config:
    ignores:
      # 需要过滤的 post 请求
      post:
        - "/api/auth/login"
        - "/api/auth/logout"
      # 需要过滤的请求，不限方法
      pattern:
        - "/test/*"
