server:
  port: 9090
spring:
  application:
    name: heifer-boot
  datasource:
    name: defaultDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxxx:3306/heifer_boot?serverTimezone=UTC
    password: xxx
    username: xxx

