spring:
  application:
    name: heifer-boot-examples
  jackson:
    default-property-inclusion: non_null
    generator:
      WRITE_NUMBERS_AS_STRINGS: true
      WRITE_BIGDECIMAL_AS_PLAIN: true
    serialization:
      INDENT_OUTPUT: false
    deserialization:
      READ_ENUMS_USING_TO_STRING: true
