spring:
  application:
    name: heifer-boot-examples
  jackson:
    default-property-inclusion: non_null
    generator:
      WRITE_BIGDECIMAL_AS_PLAIN: true
    serialization:
      INDENT_OUTPUT: false
  session:
    store-type: none
  web:
    resources:
      # 关闭静态资源
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

  cloud:
    nacos:
      server-addr: nuc8i7.wcj.plus:8848
  zipkin:
    base-url: http://nuc8i7.wcj.plus:9411
server:
  # 端口
  port: 8725
  # GZIP 压缩
#  compression:
#    enabled: true
  error:
    whitelabel:
      # 是否启用在服务器错误时在浏览器中显示的默认错误页面
      enabled: false
  servlet:
    session:
      cookie:
        max-age: -1
      timeout: -1
  tomcat:
    # 当所有可能的请求处理线程都在使用时，传入连接请求的最大队列长度。
    accept-count: 100
    # 服务器在任何给定时间接受和处理的最大连接数。一旦达到限制，操作系统仍然可以根据“acceptCount”属性接受连接。
    max-connections: 8192
    #
    threads:
      max: 200
      min-spare: 10
heifer:
  apisix:
    server-addr: http://nuc8i7.wcj.plus:9080
    server-path: apisix/admin/
    token: edd1c9f034335f136f87ad84b625c8f1
#logging:
  #  pattern:
  #    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(-){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(%M[%L]) %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
#  level:
#    plus.wcj.heifer.boot.mvc.ResultExceptionHandler: debug
#    plus.wcj.heifer.boot.common.mvc.result.ResultResponseEntityExceptionHandler: debug
#    plus.wcj.heifer.boot.common.security.filter.JwtAuthenticationFilter: debug
#    #    org.springframework.web.filter.CommonsRequestLoggingFilter: debug  # 请求报文打印
#    org.springframework.web: debug   # 请求报文打印
#    org.springframework.cache: trace # 缓存打印
#    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace # 启动时打印Mapping集合

logging:
  logstash:
    destination: nuc8i7.wcj.plus:5044


