spring:
  application:
    name: heifer-common-feign-example
  cloud:
    nacos:
      discovery:
        server-addr: heifer.wcj.plus
feign:
  okhttp:
    enabled: false
  httpclient:
    enabled: true
libby:
  ok-http:
    cache-directory: "./libby"
    cache-max-size: 2105131412
  httpclient:
    cache-type: MEMORY
    cache-directory: "./libby"
    max-object-size: 210513
    max-cache-entries: 1412
