spring:
  application:
    name: heifer-common-feign-example
  cloud:
    nacos:
      discovery:
        server-addr: heifer.wcj.plus
feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false