@userToken=Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDcyODA2Mzc4NzgwODg5MDg4Iiwic3ViIjoidXNlciIsImlhdCI6MTYyMTM5MzUxNSwicm9sZXMiOlsi5pmu6YCa55So5oi3Il0sImF1dGhvcml0aWVzIjpbeyJhdXRob3JpdHkiOiJwYWdlOnRlc3QifSx7ImF1dGhvcml0eSI6ImJ0bjp0ZXN0OnF1ZXJ5In1dLCJleHAiOjE2MjMwOTg1NDh9.O0wdVfONOm55vMTsIhTxnhRlFT6KYTcd8q8koFxwM00
@adminToken=Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDcyODA2Mzc3NjYxMDA5OTIwIiwic3ViIjoiYWRtaW4iLCJpYXQiOjE2MjEzOTM1MzAsInJvbGVzIjpbIueuoeeQhuWRmCJdLCJhdXRob3JpdGllcyI6W3siYXV0aG9yaXR5IjoicGFnZTp0ZXN0In0seyJhdXRob3JpdHkiOiJidG46dGVzdDpxdWVyeSJ9LHsiYXV0aG9yaXR5IjoiYnRuOnRlc3Q6aW5zZXJ0In0seyJhdXRob3JpdHkiOiJwYWdlOm1vbml0b3I6b25saW5lIn0seyJhdXRob3JpdHkiOiJidG46bW9uaXRvcjpvbmxpbmU6cXVlcnkifSx7ImF1dGhvcml0eSI6ImJ0bjptb25pdG9yOm9ubGluZTpraWNrb3V0In1dLCJleHAiOjE2MjMwOTg1NjN9.G853eqVReNmwiRedsbg3F7Q1hkQNHhDVobHq1BUT7PE
###
POST http://localhost:9090/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "usernameOrEmailOrPhone": "admin",
  "password": "123456"
}

###
GET  http://localhost:9876/demo/api/monitor/online/user HTTP/1.1
Content-Type: application/json
# Authorization: {{adminToken}}
Authorization: {{userToken}}



###
GET  http://localhost:9876/demo/api/monitor/online/user HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDcyODA2Mzc4NzgwODg5MDg4Iiwic3ViIjoidXNlciIsImlhdCI6MTYyMTMyNzMyOCwicm9sZXMiOlsi5pmu6YCa55So5oi3Il0sImF1dGhvcml0aWVzIjpbeyJhdXRob3JpdHkiOiJwYWdlOnRlc3QifSx7ImF1dGhvcml0eSI6ImJ0bjp0ZXN0OnF1ZXJ5In1dLCJleHAiOjE2MjEzMjc5Mjh9._sUf3nZLQJRr-guZSFz4XZH4K75uvTXguYHRou7HSXI


###
GET  http://localhost:9876/demo/test/ HTTP/1.1
Content-Type: application/json

###
GET  http://localhost:9876/demo/test/v2/ HTTP/1.1
Content-Type: application/json
Authorization: {{adminToken}}
Authorization: {{userToken}}

###
POST  http://localhost:9876/demo/test/v2/ HTTP/1.1
Content-Type: application/json
Authorization: {{adminToken}}
Authorization: {{userToken}}

###
GET  http://localhost:9876/demo/api/monitor/online/user HTTP/1.1
Content-Type: application/json
# Authorization: {{adminToken}}
Authorization: {{userToken}}
