server:
    port: 8080
spring:
    application:
        name: heifer-boot
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        name: defaultDataSource
        password: '***'
        url: jdbc:mysql://localhost:3306/blue?serverTimezone=UTC
        username: '***'
