spring:
  application:
    name: heifer-common-mybatis-plus-example
  # DataSource Config
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    url: jdbc:h2:mem:test
    username: root
    password: test
  cloud:
    nacos:
      server-addr: nuc8i7.wcj.plus:8848
mybatis-plus:
  # xml影射路径
  mapper-locations: classpath*:/mapper/*.xml